**WEEK 3: Dictionary and Numpy**

Dictionary contains data that has key-value pair
The value can be either str, float, boolean, int and list



1.   A dictionary is mutable-changeable
2.   A dictionary can be overwritten



In [2]:
mydict ={"Name": "Thomas", "Country":"Ghana", "Profession":"Lecturer", "years": 5, "height":5.9}

In [3]:
mydict

{'Name': 'Thomas',
 'Country': 'Ghana',
 'Profession': 'Lecturer',
 'years': 5,
 'height': 5.9}

In [4]:
#accessing the dictionary
mydict['Name']


'Thomas'

In [5]:
mydict.get('Name')

'Thomas'

In [6]:
mydict.get('years')

5

In [7]:
#changing specific values
mydict['Name']="Ngozi"


In [8]:
print(mydict)

{'Name': 'Ngozi', 'Country': 'Ghana', 'Profession': 'Lecturer', 'years': 5, 'height': 5.9}


In [9]:
mydict.update({"Name": "Samuel"})

In [10]:
mydict

{'Name': 'Samuel',
 'Country': 'Ghana',
 'Profession': 'Lecturer',
 'years': 5,
 'height': 5.9}

In [11]:
#adding new key-value pair
mydict.update({"is_graduated":True})

In [12]:
mydict

{'Name': 'Samuel',
 'Country': 'Ghana',
 'Profession': 'Lecturer',
 'years': 5,
 'height': 5.9,
 'is_graduated': True}

In [13]:
mydict['race'] ='white'

In [14]:
mydict

{'Name': 'Samuel',
 'Country': 'Ghana',
 'Profession': 'Lecturer',
 'years': 5,
 'height': 5.9,
 'is_graduated': True,
 'race': 'white'}

In [15]:
#copy the old dict into a new dict
mydict2 =mydict.copy()

In [16]:
mydict2

{'Name': 'Samuel',
 'Country': 'Ghana',
 'Profession': 'Lecturer',
 'years': 5,
 'height': 5.9,
 'is_graduated': True,
 'race': 'white'}

In [17]:
#removing items
mydict.pop('years')

5

In [18]:
mydict

{'Name': 'Samuel',
 'Country': 'Ghana',
 'Profession': 'Lecturer',
 'height': 5.9,
 'is_graduated': True,
 'race': 'white'}

In [19]:
mydict.popitem()

('race', 'white')

In [20]:
mydict

{'Name': 'Samuel',
 'Country': 'Ghana',
 'Profession': 'Lecturer',
 'height': 5.9,
 'is_graduated': True}

In [21]:
mydict3 =mydict.copy()

In [22]:
mydict3

{'Name': 'Samuel',
 'Country': 'Ghana',
 'Profession': 'Lecturer',
 'height': 5.9,
 'is_graduated': True}

In [23]:
#deleting the entire dictionary
del mydict

In [24]:
mydict3.clear()

In [25]:
mydict3

{}

In [29]:
mydict2.items()

dict_items([('Name', 'Samuel'), ('Country', 'Ghana'), ('Profession', 'Lecturer'), ('years', 5), ('height', 5.9), ('is_graduated', True), ('race', 'white')])

In [30]:
#looping through dictionary
#loop through keys
for i in mydict2.keys():
  print(i)


Name
Country
Profession
years
height
is_graduated
race


In [31]:
#loop through values
for i in mydict2:
  print(mydict2[i])

Samuel
Ghana
Lecturer
5
5.9
True
white


In [32]:
#grab both the key and the value
for i, j in mydict2.items():
  print(i,j)

Name Samuel
Country Ghana
Profession Lecturer
years 5
height 5.9
is_graduated True
race white


In [33]:
#nested dictionary
stud1 ={'Test': 92, 'Grade':'A'}

stud2 ={'Test': 85, 'Grade':'B'}

stud3 ={'Test': 75, 'Grade': 'C'}
 
stud4 ={'Test': 90, 'Grade': 'A'}

stud5 ={'Test': 59, 'Grade': 'F'}


mystud ={'s1': stud1, 's2': stud2, 's3': stud3, 's4':stud4, 's5':stud5}


In [ ]:
mystud

{'s1': {'Test': 92, 'Grade': 'A'},
 's2': {'Test': 85, 'Grade': 'B'},
 's3': {'Test': 75, 'Grade': 'C'},
 's4': {'Test': 90, 'Grade': 'A'},
 's5': {'Test': 59, 'Grade': 'F'}}

In [ ]:
mystud.get('s1')

{'Test': 92, 'Grade': 'A'}

In [ ]:
mystud['s1']

{'Test': 92, 'Grade': 'A'}

In [ ]:
mys1 =mystud['s1']

mys1['Grade']

'A'

In [34]:
##write a program that combines 5 dictionaries of sales personnel which contains their names and sales made

sales_p1 ={'name': 'Daniel', 'sales': 5000.00}
sales_p2 ={'name': 'Sarah', 'sales': 4500.00}
sales_p3 ={'name': 'Aisha', 'sales': 6500.00}
sales_p4 ={'name': 'Seyi', 'sales': 5500.00}
sales_p5 ={'name': 'Chike', 'sales': 7000.00}

sales = {'s1': sales_p1, 's2': sales_p2, 's3': sales_p3, 's4': sales_p4, 's5': sales_p5}

sales

{'s1': {'name': 'Daniel', 'sales': 5000.0},
 's2': {'name': 'Sarah', 'sales': 4500.0},
 's3': {'name': 'Aisha', 'sales': 6500.0},
 's4': {'name': 'Seyi', 'sales': 5500.0},
 's5': {'name': 'Chike', 'sales': 7000.0}}

In [43]:
sales['s1'].keys()

dict_values(['Daniel', 5000.0])

In [44]:
sales['s1'].values()

dict_values(['Daniel', 5000.0])

In [1]:
##September 1st 
#Numpy

In [2]:
#vector
v =[1, 2, 3,4, 5]
v

[1, 2, 3, 4, 5]

In [4]:
#matrix
mat =[v, v]
mat

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]

**Numpy** is an N-dimensional array
It is a module in python that has an extensive application to the following areas


1.   Linear algebra
2.   Statistics


1.   Applied Math
2.   Geometry





In [5]:
#Focus
#Basic operations on arrays
#"Data Containers"
#Resize arrays
#Stack arrays
#Slicing
#other stuff

In [31]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [6]:
import numpy as np
import matplotlib.pyplot as plt


In [7]:
#1D array
arr =np.array([1,2,3,4])
arr


array([1, 2, 3, 4])

In [8]:
#Basic operations on arrays
arr1 =np.array([2,4, 5, 9])
#add two arrays
add_arr =arr +arr1
add_arr


array([ 3,  6,  8, 13])

In [9]:
#subtract two arrays
sub_arr =arr1 -arr
sub_arr

array([1, 2, 2, 5])

In [10]:
#scalar mult
scal =2*arr1
scal

array([ 4,  8, 10, 18])

In [11]:
#"Data Containers"
#zeros
#ones
#eye
#arange vs linspace

In [13]:
arr_zero =np.zeros((10,6), dtype=float)

In [14]:
arr_zero

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
arr_one=np.ones((10,6), dtype=float)

In [16]:
arr_one 

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
arr_one =0.5*arr_one
arr_one

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]])

In [18]:
arr_eye =np.eye(3)
arr_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
#arange vs linspace
arr_arange =np.arange(0, 50+1, 0.4)
arr_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [26]:
arr_lin =np.linspace(0, 50,100)
arr_lin

array([ 0.        ,  0.50505051,  1.01010101,  1.51515152,  2.02020202,
        2.52525253,  3.03030303,  3.53535354,  4.04040404,  4.54545455,
        5.05050505,  5.55555556,  6.06060606,  6.56565657,  7.07070707,
        7.57575758,  8.08080808,  8.58585859,  9.09090909,  9.5959596 ,
       10.1010101 , 10.60606061, 11.11111111, 11.61616162, 12.12121212,
       12.62626263, 13.13131313, 13.63636364, 14.14141414, 14.64646465,
       15.15151515, 15.65656566, 16.16161616, 16.66666667, 17.17171717,
       17.67676768, 18.18181818, 18.68686869, 19.19191919, 19.6969697 ,
       20.2020202 , 20.70707071, 21.21212121, 21.71717172, 22.22222222,
       22.72727273, 23.23232323, 23.73737374, 24.24242424, 24.74747475,
       25.25252525, 25.75757576, 26.26262626, 26.76767677, 27.27272727,
       27.77777778, 28.28282828, 28.78787879, 29.29292929, 29.7979798 ,
       30.3030303 , 30.80808081, 31.31313131, 31.81818182, 32.32323232,
       32.82828283, 33.33333333, 33.83838384, 34.34343434, 34.84

In [28]:
##Resizing arrays
#shape
arr_arange.shape


(51,)

In [29]:
#reshape method
arr_arange =arr_arange.reshape((-1, 1))
arr_arange

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49],
       [50]])

In [30]:
arr_arange.shape

(51, 1)

In [32]:
#stacking arrays
ar1 =np.array([1,2,3,4]).reshape((-1,1))
ar2 =np.array([5, 6, 7, 8]).reshape((-1,1))

ar1


array([[1],
       [2],
       [3],
       [4]])

In [33]:
ar2

array([[5],
       [6],
       [7],
       [8]])

In [34]:
#vstack
v_arr =np.vstack((ar1, ar2))
v_arr

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [35]:
#hstack
h_arr =np.hstack((ar1, ar2))
h_arr

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
#np.concatenate

In [36]:
##Slicing

In [37]:
arr_slic =0.4*np.ones((45,7), dtype=float)
arr_slic

array([[0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4,

In [42]:
##grab some rows
#5th to 10th row
arr_slic[4:10, :]  

array([[0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4]])

In [43]:
arr_slic[:5,:]=0.5

In [44]:
arr_slic

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4,

In [45]:
arr_slic[-2:, :]=0.9

In [46]:
arr_slic

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
       [0.4, 0.4, 0.4, 0.4, 0.4,

In [47]:
##grab columns
#first two columns
arr_slic[:, 0:2]

array([[0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.4, 0.4],
       [0.9, 0.9],
       [0.9, 0.9]])

In [48]:
#other stuff
np.sum(arr_arange)

1275

In [49]:
#
np.mean(arr_arange)

25.0

In [50]:
np.std(arr_arange)

14.719601443879744

In [51]:
np.min(arr_arange)

0

In [52]:
np.max(arr_arange)

50

In [53]:
np.transpose(arr_arange)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50]])

In [54]:
np.cumsum(arr_arange)

array([   0,    1,    3,    6,   10,   15,   21,   28,   36,   45,   55,
         66,   78,   91,  105,  120,  136,  153,  171,  190,  210,  231,
        253,  276,  300,  325,  351,  378,  406,  435,  465,  496,  528,
        561,  595,  630,  666,  703,  741,  780,  820,  861,  903,  946,
        990, 1035, 1081, 1128, 1176, 1225, 1275])

In [55]:
sorted(arr_arange)

[array([0]),
 array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8]),
 array([9]),
 array([10]),
 array([11]),
 array([12]),
 array([13]),
 array([14]),
 array([15]),
 array([16]),
 array([17]),
 array([18]),
 array([19]),
 array([20]),
 array([21]),
 array([22]),
 array([23]),
 array([24]),
 array([25]),
 array([26]),
 array([27]),
 array([28]),
 array([29]),
 array([30]),
 array([31]),
 array([32]),
 array([33]),
 array([34]),
 array([35]),
 array([36]),
 array([37]),
 array([38]),
 array([39]),
 array([40]),
 array([41]),
 array([42]),
 array([43]),
 array([44]),
 array([45]),
 array([46]),
 array([47]),
 array([48]),
 array([49]),
 array([50])]

In [56]:
#reverse
arr_arange[::-1]

array([[50],
       [49],
       [48],
       [47],
       [46],
       [45],
       [44],
       [43],
       [42],
       [41],
       [40],
       [39],
       [38],
       [37],
       [36],
       [35],
       [34],
       [33],
       [32],
       [31],
       [30],
       [29],
       [28],
       [27],
       [26],
       [25],
       [24],
       [23],
       [22],
       [21],
       [20],
       [19],
       [18],
       [17],
       [16],
       [15],
       [14],
       [13],
       [12],
       [11],
       [10],
       [ 9],
       [ 8],
       [ 7],
       [ 6],
       [ 5],
       [ 4],
       [ 3],
       [ 2],
       [ 1],
       [ 0]])

In [59]:
aa =np.array([[1,2], [3,4], [4,5]])

In [60]:
aa

array([[1, 2],
       [3, 4],
       [4, 5]])

In [61]:
aa.T

array([[1, 3, 4],
       [2, 4, 5]])